name: GitHub Packages

on:
  release:
    types: [published]

jobs:
  docker:
    name: Build, tag and push image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Docker Package Registry
      uses: craftech-io/package-action@v3.1.0
      with:
        dockerfile: Dockerfile
        tags: |
          latest
          ${{ github.event.release.tag_name }}
        access_token: ${{ secrets.ACCESS_TOKEN }}
