name: GitHub Packages

on:
  release:
    types: [published]

jobs:
  docker:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build, tag and push image to GitHub Packages
      uses: craftech-io/package-action@v3.1.0
      with:
        image_name: backend-docker-image
        tags: |
          latest
          ${{ github.event.release.tag_name }}
        dockerfile: Dockerfile
        access_token: ${{ secrets.ACCESS_TOKEN }}
